SELECT DISTINCT t.DocDesc
FROM "PR_ADTRANS_ARC" AS t
JOIN "PR_ADTRANSLN_ARC" AS ln ON t.ID = ln.MasterID
WHERE t.EmpCode IN (
    SELECT "HR_EMPLOYEE"."EmpCode"
    FROM "HR_EMPLOYEE"
    JOIN "HR_GANGLN" ON "HR_GANGLN"."GangMember" = "HR_EMPLOYEE"."EmpCode"
    WHERE "HR_GANGLN"."GangCode" = 'C1H'
)
AND t.DocDate >= '2025-05-01'
AND t.DocDate < '2025-06-01'
ORDER BY t.DocDesc;