SELECT SUM(LFLN.Amount) AS TotalAmount
FROM "PR_LOOSEFRUIT" LF
JOIN "PR_LOOSEFRUITLN" LFLN
  ON LF.ID = LFLN.MasterID
WHERE LFLN.EmpCode LIKE 'H0510'
  AND LF.DocDate >= '2025-05-01'
  AND LF.DocDate < '2025-06-01'
